import { courseImages } from 'assets/images/courses';

import type { CourseLevel } from './levels';

export type { CourseLevel } from './levels';

export type CourseConfigItem = {
  id: number;
  name: string;
  type: string;
  teacher: string;
  level: CourseLevel;
  dateFrom: string;
  dateTo: string;
  price: number;
  image: string;
  studio: string;
  weekdays: string[];
  timeFrom: string;
  timeTo: string;
};

export const COURSES_CONFIG: CourseConfigItem[] = [
  {
    id: 1,
    name: 'Интенсив по High Heels',
    type: 'High Heels',
    teacher: 'Карпова Ксения',
    level: 'Intermediate',
    dateFrom: '02.02',
    dateTo: '14.02',
    price: 10000,
    image: courseImages.highHeels1,
    studio: 'ТанцХаб',
    weekdays: ['monday', 'wednesday', 'friday'],
    timeFrom: '19:00',
    timeTo: '20:30',
  },
  {
    id: 2,
    name: 'High Heels с нуля',
    type: 'High Heels',
    teacher: 'Иванова Мария',
    level: 'Beginner',
    dateFrom: '03.02',
    dateTo: '15.02',
    price: 8000,
    image: courseImages.highHeels2,
    studio: 'DanceLab',
    weekdays: ['tuesday', 'thursday'],
    timeFrom: '18:00',
    timeTo: '19:30',
  },
  {
    id: 3,
    name: 'Основы Contemporary',
    type: 'Contemporary',
    teacher: 'Смирнова Анна',
    level: 'Intermediate',
    dateFrom: '05.02',
    dateTo: '20.02',
    price: 9500,
    image: courseImages.contemporary,
    studio: 'Студия движения',
    weekdays: ['monday', 'wednesday'],
    timeFrom: '17:00',
    timeTo: '18:30',
  },
  {
    id: 4,
    name: 'Jazz Funk для начинающих',
    type: 'Jazz Funk',
    teacher: 'Орлова Дарья',
    level: 'Beginner',
    dateFrom: '10.02',
    dateTo: '22.02',
    price: 7000,
    image: courseImages.jazzFunk,
    studio: 'Арт-пространство',
    weekdays: ['tuesday', 'thursday', 'saturday'],
    timeFrom: '12:00',
    timeTo: '13:30',
  },
  {
    id: 5,
    name: 'Vogue: продвинутый уровень',
    type: 'Vogue',
    teacher: 'Кузнецов Артём',
    level: 'Advanced',
    dateFrom: '15.02',
    dateTo: '28.02',
    price: 12000,
    image: courseImages.vogue,
    studio: 'Грация',
    weekdays: ['wednesday', 'friday'],
    timeFrom: '20:00',
    timeTo: '21:30',
  },
  {
    id: 6,
    name: 'Hip-Hop: новая волна',
    type: 'Hip-Hop',
    teacher: 'Павлова Елена',
    level: 'Intermediate',
    dateFrom: '16.02',
    dateTo: '28.02',
    price: 9000,
    image: courseImages.hipHop,
    studio: 'ТанцХаб',
    weekdays: ['monday', 'thursday'],
    timeFrom: '18:00',
    timeTo: '19:30',
  },
  {
    id: 7,
    name: 'Dancehall: первые шаги',
    type: 'Dancehall',
    teacher: 'Мельникова Ольга',
    level: 'Beginner',
    dateFrom: '18.02',
    dateTo: '28.02',
    price: 7500,
    image: courseImages.dancehall,
    studio: 'DanceLab',
    weekdays: ['tuesday', 'saturday'],
    timeFrom: '14:00',
    timeTo: '15:30',
  },
  {
    id: 8,
    name: 'Frame Up: мастерский класс',
    type: 'Frame Up',
    teacher: 'Карпова Ксения',
    level: 'Advanced',
    dateFrom: '20.02',
    dateTo: '05.03',
    price: 13000,
    image: courseImages.frameUp,
    studio: 'Арт-пространство',
    weekdays: ['monday', 'wednesday', 'friday'],
    timeFrom: '20:00',
    timeTo: '21:30',
  },
  {
    id: 9,
    name: 'Stretching для начинающих',
    type: 'Stretching',
    teacher: 'Лебедева Ирина',
    level: 'Beginner',
    dateFrom: '01.03',
    dateTo: '12.03',
    price: 6000,
    image: courseImages.stretching,
    studio: 'Студия движения',
    weekdays: ['tuesday', 'thursday', 'saturday'],
    timeFrom: '10:00',
    timeTo: '11:30',
  },
  {
    id: 10,
    name: 'Lady Style: грация и пластика',
    type: 'Lady Style',
    teacher: 'Соколова Полина',
    level: 'Intermediate',
    dateFrom: '03.03',
    dateTo: '16.03',
    price: 9000,
    image: courseImages.ladyStyle,
    studio: 'Грация',
    weekdays: ['monday', 'wednesday'],
    timeFrom: '19:00',
    timeTo: '20:30',
  },
  {
    id: 11,
    name: 'Heels Choreography: постановка',
    type: 'Heels Choreography',
    teacher: 'Карпова Ксения',
    level: 'Advanced',
    dateFrom: '10.03',
    dateTo: '25.03',
    price: 14000,
    image: courseImages.heelsChoreography,
    studio: 'ТанцХаб',
    weekdays: ['tuesday', 'friday'],
    timeFrom: '20:00',
    timeTo: '21:30',
  },
  {
    id: 13,
    name: 'K-Pop: танцуем хиты',
    type: 'K-Pop',
    teacher: 'Чжан Лина',
    level: 'Intermediate',
    dateFrom: '01.04',
    dateTo: '15.04',
    price: 9500,
    image: courseImages.kPop,
    studio: 'DanceLab',
    weekdays: ['wednesday', 'saturday'],
    timeFrom: '15:00',
    timeTo: '16:30',
  },
  {
    id: 14,
    name: 'Afro Dance с нуля',
    type: 'Afro Dance',
    teacher: 'Абдуллаев Тимур',
    level: 'Beginner',
    dateFrom: '03.04',
    dateTo: '18.04',
    price: 8500,
    image: courseImages.afroDance,
    studio: 'Арт-пространство',
    weekdays: ['monday', 'thursday'],
    timeFrom: '16:00',
    timeTo: '17:30',
  },
  {
    id: 15,
    name: 'Waacking: экспрессия движения',
    type: 'Waacking',
    teacher: 'Громова Юлия',
    level: 'Advanced',
    dateFrom: '05.04',
    dateTo: '20.04',
    price: 12000,
    image: courseImages.waacking,
    studio: 'Грация',
    weekdays: ['tuesday', 'friday'],
    timeFrom: '19:00',
    timeTo: '20:30',
  },
  {
    id: 18,
    name: 'House Dance: ритм и грув',
    type: 'House Dance',
    teacher: 'Беляева София',
    level: 'Intermediate',
    dateFrom: '15.04',
    dateTo: '30.04',
    price: 9000,
    image: courseImages.houseDance,
    studio: 'Студия движения',
    weekdays: ['wednesday', 'friday'],
    timeFrom: '18:00',
    timeTo: '19:30',
  },
  {
    id: 19,
    name: 'Breakdance: мастер-класс',
    type: 'Breakdance',
    teacher: 'Наумов Максим',
    level: 'Advanced',
    dateFrom: '01.05',
    dateTo: '16.05',
    price: 13000,
    image: courseImages.breakdance,
    studio: 'ТанцХаб',
    weekdays: ['monday', 'wednesday', 'saturday'],
    timeFrom: '17:00',
    timeTo: '18:30',
  },
  {
    id: 20,
    name: 'Twerk для начинающих',
    type: 'Twerk',
    teacher: 'Лазарева Виктория',
    level: 'Beginner',
    dateFrom: '05.05',
    dateTo: '20.05',
    price: 8500,
    image: courseImages.twerk,
    studio: 'DanceLab',
    weekdays: ['tuesday', 'thursday'],
    timeFrom: '20:00',
    timeTo: '21:30',
  },
  {
    id: 21,
    name: 'Salsa: ритмы Латины',
    type: 'Salsa',
    teacher: 'Гарсия Марко',
    level: 'Beginner',
    dateFrom: '10.05',
    dateTo: '25.05',
    price: 8000,
    image: courseImages.salsa,
    studio: 'Арт-пространство',
    weekdays: ['wednesday', 'friday', 'sunday'],
    timeFrom: '19:00',
    timeTo: '20:30',
  },
  {
    id: 22,
    name: 'Bachata: чувственный танец',
    type: 'Bachata',
    teacher: 'Рамирес Луис',
    level: 'Intermediate',
    dateFrom: '12.05',
    dateTo: '27.05',
    price: 9000,
    image: courseImages.bachata,
    studio: 'Грация',
    weekdays: ['thursday', 'saturday'],
    timeFrom: '19:00',
    timeTo: '20:30',
  },
  {
    id: 24,
    name: 'Авторская хореография',
    type: 'Choreo Class',
    teacher: 'Карпова Ксения',
    level: 'Intermediate',
    dateFrom: '18.05',
    dateTo: '02.06',
    price: 10000,
    image: courseImages.choreoClass,
    studio: 'Студия движения',
    weekdays: ['monday', 'wednesday'],
    timeFrom: '20:00',
    timeTo: '21:30',
  },
];
